name: compile routingkit
on:
  workflow_dispatch:  # Allow manual trigger

defaults:
  run:
    working-directory: ./third_party

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
        - os: macos-latest
          TARGET: darwin-x86_64
        - os: ubuntu-latest
          TARGET: linux-x86_64
    steps:
      - uses: actions/checkout@v2
      - run: echo "Compiling for ${{matrix.TARGET}}"
      - name: Compile for macos
        run: |
          echo ">>> Running setup.sh"
          bash setup.sh
          echo ">>> Running build.sh"
          bash build.sh

      - name: Commit files
        run: |
          git config --local user.email "bot@nextmv.io"
          git config --local user.name "nextmv bot"
          git add --all
          git commit -m "Adding macos binaries"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
