name: go-routingkit test
on: [push]

jobs:
  build:
    name: go-routingkit test
    runs-on: ubuntu-latest
    env:
      working-directory: ./routingkit
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      # Clone the repo
      - name: git clone
        uses: actions/checkout@v2

      # Build the module
      - name: go build
        run: go build -race -v ./...
        working-directory: ${{env.working-directory}}

      # Run the tests
      - name: go test
        run: go test -cover -race ./...
        working-directory: ${{env.working-directory}}
