name: go-routingkit test
on: [push]

jobs:
  build:
    name: go-routingkit test
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      # Clone the repo
      - name: git clone
        uses: actions/checkout@v2

      # Build the everything
      - name: go build
        run: go build -v ./...

      # Run the tests
      - name: go test
        run: go test -v -cover -race ./... -args -clean_ch=false
