name: test compile routingkit
on: [push]

defaults:
  run:
    working-directory: ./third_party

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # Forbid parallel builds (may cause problems with git commits)
      max-parallel: 1
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: echo "Compiling for ${{matrix.os}}"
      - name: Info
        run: |
          echo ">>> uname -a"
          uname -a || echo "failed getting system info"
          echo ">>> g++"
          g++ --version || echo "failed getting g++ version"
          echo ">>> clang++"
          clang++ --version || echo "failed getting clang++ version"
          echo ">>> glibc"
          ldd --version || echo "failed getting glibc version"
          echo ">>> ar"
          ar --version || echo "failed getting ar version"
          echo ">>> swig"
          swig -version || echo "failed getting swig version"
      - name: Compile
        run: |
          echo ">>> Running setup.sh"
          bash setup.sh
          echo ">>> Running build.sh"
          bash build.sh
      - name: Test
        run: go test -v -cover -race ./... -args -clean_ch=false
        working-directory: .
